using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;

namespace ShopMate.GUI
{
    public sealed partial class ViewReportsPage : Page
    {
        public ViewReportsPage()
        {
            // Ensure the partial class is generated by the XAML compiler
            this.InitializeComponent();
        }

        private void OnBackClicked(object sender, RoutedEventArgs e)
        {
            // TODO: Navigate back to AdminDashboardPage
        }

        private void ViewReport_Click(object sender, RoutedEventArgs e)
        {
            // TODO: Filter report by selected month/year
        }
    }
}
